name: Vault-plan

on:
  push:
    branches:
      - backup-vault

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.1.0"

      - name: Terraform init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check
          
      - name: Terraform Plan
        run: terraform plan
