name: Terraform

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.1.0"

      - name: Terraform init
        run: terraform init

      - name: Import EC2 instances
        run: |
          terraform import aws_instance.example_instance[0] i-0fae66b6348bdb0a2
          terraform import aws_instance.example_instance[1] i-0410e332568b4595d
          

      - name: Terraform plan
        run: terraform plan
