name: 'alt-backup-vault-plan-new'

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: "alt-backup-vault"


env:
  terraform_version: "latest"
  path: /opt/actions-runner/_work/alt-ops-aws-backup-vault/    

jobs:
  terraform-plan:
    defaults:
        run:
          working-directory: ./alt-vault-backup
    runs-on: [self-hosted, Linux]
    environment:
      name: ${{ inputs.environment }}

    permissions:
      id-token: write
      contents: read


    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT }}:role/${{ vars.AWS_ORCHESTRATION_ROLE }}
          role-duration-seconds: 900
          aws-region: ${{ vars.AWS_REGION }}

      - name: list file 
        run: ls -la    

      - name: Install additional software
        run: "sudo apt-get update && sudo apt-get install unzip"

      - name: Setup Node JS version 18.x
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{env.terraform_version}}

      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Format
        run: terraform fmt -check
          
      - name: Terraform Plan
        id: plan
        run: terraform plan 