name: Vault

on:
  push:
    branches:
      - backup-vault
 


env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.1.0"
      
      - name: List files in directory
        run: ls -la

      - name: Change script permission
        run: |
          chmod 755 role.sh
          ls -la
          
      - name: run shell script
        run: ./role.sh    
  
      - name: Terraform init
        run: terraform init
          
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        continue-on-error: true

