name: vault

on:
  push:
    branches:
      - backup-vault

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.1.0"

      - name: Terraform init
        run: terraform init
          
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        continue-on-error: true

      - name: Check Terraform Plan Status
        run: |
          if [ ${{ steps.plan.outcome }} == "success" ]; then
            echo "Terraform plan succeeded, proceeding to apply changes."
          else
            echo "Terraform plan failed. Check the logs for errors."
            exit 1
          fi

      - name: Terraform Apply
        if: success() && github.event_name == 'push'
        run: terraform apply tfplan